/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.6-rc-1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    java
}

repositories {
    mavenCentral()
}

dependencies {
    implementation ("org.junit.jupiter:junit-jupiter:+") // 5.10.1  https://junit.org/junit5/
    implementation ("org.mockito:mockito-core:+") // 5.8.0  https://site.mockito.org/
    implementation ("com.google.truth:truth:+")   // 1.2.0  https://truth.dev/
    implementation ("edu.cnu.cs:gooey:1.0.11.05")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}
